### PR TITLE
OPL-39: Provide Insuree picker and Family picker for Invoice module

### PR DESCRIPTION
**Pull request by rstencel**

### CODE REVIEW

**Comment by delcroip** [comment]
@rstencel  thanks for the projections

regarding the contribution,  we need this contribution but I am wondering if there is a "loose" compiling way add this contribution, could we add this picker via the calcrule ?

fyi @qgerome @edarchis

**Comment by qgerome** [comment]
I think the question is more : "Why do you need to add `invoice.SubjectAndThirdpartyPicker` since both pickers are already available to other modules using the `PublishedComponent` component ?" I would prefer to keep it each module as much as possible without links to other modules.

**Comment by qgerome** [comment]
From what I understand based on the changes in this pull request, you do not use the `modulesManager.getRef('insuree.InsureePicker.projection')`

**Comment by rstencel** [comment]
> I think the question is more : "Why do you need to add `invoice.SubjectAndThirdpartyPicker` since both pickers are already available to other modules using the `PublishedComponent` component ?" I would prefer to keep each module as much as possible without additions required for other modules.

This contribution point has been added with this complex structure because in Invoice frontend module there is no hardcoded information about which exposed component to use when subject/thirdparty is of certain type. To make it generic the modules exporting the components can tell the Invoice frontend module which component ("picker" property) to use in case of certain type of subject/thirdparty ("type" property) and what data is required by the picker to display the value correctly ("pickerProjection" property). 

If there exists a source of information about which component to use when subject/thirdparty is of certain type (one could say - mapping) then the Invoice frontend module could use an exposed component from a certain module by using `modulesManager.getRef(...)` without the need of a contribution of this module to `invoice.SubjectAndThirdpartyPicker`.

**Comment by delcroip** [comment]
@rstencel @qgerome  Thank you.

is '''"insuree":"insuree.InsureePicker.projection"''' enough "information for '''modulesManager.getRef(...)''' or will you need more  ? 

if it is enough, I think we could maybe defined it a the invoice/calculation configuration exposed to FE

**Comment by qgerome** [comment]
> > I think the question is more : "Why do you need to add `invoice.SubjectAndThirdpartyPicker` since both pickers are already available to other modules using the `PublishedComponent` component ?" I would prefer to keep each module as much as possible without additions required for other modules.
> 
> This contribution point has been added with this complex structure because in Invoice frontend module there is no hardcoded information about which exposed component to use when subject/thirdparty is of certain type. To make it generic the modules exporting the components can tell the Invoice frontend module which component ("picker" property) to use in case of certain type of subject/thirdparty ("type" property) and what data is required by the picker to display the value correctly ("pickerProjection" property).
> 
> If there exists a source of information about which component to use when subject/thirdparty is of certain type (one could say - mapping) then the Invoice frontend module could use an exposed component from a certain module by using `modulesManager.getRef(...)` without the need of a contribution of this module to `invoice.SubjectAndThirdpartyPicker`.

In this case, I'd recommend to have a component in the invoice module that will use the right picker/renderer based on the subject/thirdparty.

**Comment by delcroip** [comment]
> 

@qgerome  fyi, the module might not know the possible  subject/thirdparty because they are defined by "converter"  in other modules (calculation) that why I'd like to have a way to configure it outside of the code base: if you add a "converter" in the BE module assembly then you could simply "configure" the invoice module to use the right picker (as long as there is on exposed) without creating a new invoice module

**Comment by rstencel** [comment]
> @rstencel @qgerome Thank you.
> 
> is `"insuree":"insuree.InsureePicker.projection"` enough information for `modulesManager.getRef(...)` or will you need more ?
> 
> if it is enough, I think we could maybe defined it a the invoice/calculation configuration exposed to FE

I would need the pickers ref name (in this case "insuree.InsureePicker") and its projection ref name (in this case "insuree.InsureePicker.projection")

**Review by delcroip — APPROVED** [review]
To be updated later

**Pull request merged**
